### ISSUE TITLE
FrontEnd: create a new react component to show breadcrumbs

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#34]
The website is in React/nextjs. you can check out the live version.
we are using material-ui.

From home, if you click on learn more, a new page comes.
Here, in foodDetails.js,
there should be breadcrumb shown just below the navigation menu.

For more information comment.

**Comment by konsvasi** [comment]
Hey, I'd like to try this out. Do you any idea where the breadcrumb should be placed so that it looks good? Maybe under the home and about buttons?

**Comment by drex44** [comment]
yes, @konsvasi It should be below the home and about buttons.
For example, In GitHub where the username/repo is shown is a perfect example of effective breadcrumb.

**Comment by konsvasi** [comment]
Ok, I'll take a look

**Comment by konsvasi** [comment]
One question, I managed to extract the path from the props which looks like this `/foodDetails/` + the title of the illness. But this doesn't look like a correct path because when I go back I visit the home page and not `localhost:3000/foodDetails` shouldn't the correct path be something like `home/illness`? I was thinking of making the breadcrumbs clickable but this would lead the user to the empty `foodDetails` page when the user clicks this option.

**Comment by drex44** [comment]
@konsvasi 
currently, we have only three pages. home, foodDetails and about. so the breadcrumbs will be like that only,
home > foodDetails > [illness name]
As per the structure, we cannot use foodDetails as a clickable because it does not show anything without the name of the illness. 

so what you can do right now is create a breadcrumbs component which accepts "elements" as a prop.
this "elements" will be an array of object({title:"",link:""}).
so your element will parse it and give breadcrumb in response.
one more prop will be "clickable". so if it is true, it will show clickable elements otherwise not clickable.

**Comment by konsvasi** [comment]
Okay, I'll adjust my code, thanks.

**Comment by maafaishal** [comment]
I've fixed this issue. Pls check my PR#54

**Comment by drex44** [comment]
closed by PR #54
